"""Regression policy for the project-local Python dependency graph."""

from __future__ import annotations

import re
import subprocess
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
BUILTIN_SKILL_REQUIREMENTS = tuple(
    sorted((ROOT / "skills" / "builtin").glob("*/scripts/requirements.txt"))
)


def _normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _requirement_name(requirement: str) -> str:
    return _normalize(re.split(r"[<>=!~;\[ ]", requirement, maxsplit=1)[0])


def _declared_dependencies() -> set[str]:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    return {_requirement_name(item) for item in project["project"]["dependencies"]}


def _builtin_skill_dependencies() -> set[str]:
    dependencies: set[str] = set()
    for requirements_file in BUILTIN_SKILL_REQUIREMENTS:
        for raw_line in requirements_file.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if line and not line.startswith("#"):
                dependencies.add(_requirement_name(line))
    return dependencies


def _lock_data() -> dict:
    return tomllib.loads((ROOT / "uv.lock").read_text(encoding="utf-8"))


def _locked_packages() -> set[str]:
    lock = _lock_data()
    return {_normalize(package["name"]) for package in lock["package"]}


def _locked_direct_dependencies() -> set[str]:
    project_package = next(
        package for package in _lock_data()["package"]
        if package["name"] == "agent-builder"
    )
    return {_normalize(dependency["name"]) for dependency in project_package["dependencies"]}


def _exported_packages() -> set[str]:
    packages: set[str] = set()
    for raw_line in (ROOT / "requirements.txt").read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith(("#", "--")):
            continue
        packages.add(_requirement_name(line))
    return packages


LEGACY_OR_EXTERNAL_RUNTIME_PACKAGES = {
    "anaconda",
    "conda",
    "docker",
    "gradio",
    "gradio-client",
    "miniconda",
    "podman",
}

REQUIRED_OBSERVABILITY_PACKAGES = {
    "arize-phoenix",
    "arize-phoenix-otel",
    "openinference-semantic-conventions",
    "opentelemetry-api",
    "opentelemetry-exporter-otlp-proto-http",
    "opentelemetry-sdk",
}

REQUIRED_BUILTIN_SKILL_PACKAGES = {
    "defusedxml",
    "lxml",
    "openpyxl",
    "pandas",
    "pdfplumber",
    "pillow",
    "pypdf",
    "pypdfium2",
    "python-docx",
    "reportlab",
}


def test_direct_dependencies_follow_runtime_policy() -> None:
    declared = _declared_dependencies()
    assert not declared & LEGACY_OR_EXTERNAL_RUNTIME_PACKAGES
    assert REQUIRED_OBSERVABILITY_PACKAGES <= declared
    assert REQUIRED_BUILTIN_SKILL_PACKAGES <= declared
    assert _builtin_skill_dependencies() <= declared


def test_lock_and_compatibility_export_exclude_legacy_packages() -> None:
    locked = _locked_packages()
    exported = _exported_packages()
    assert not locked & LEGACY_OR_EXTERNAL_RUNTIME_PACKAGES
    assert not exported & LEGACY_OR_EXTERNAL_RUNTIME_PACKAGES
    assert REQUIRED_OBSERVABILITY_PACKAGES <= locked
    assert REQUIRED_BUILTIN_SKILL_PACKAGES <= locked
    assert _locked_direct_dependencies() == _declared_dependencies()
    assert _declared_dependencies() <= exported


def test_requirements_is_a_uv_generated_production_export() -> None:
    header = (ROOT / "requirements.txt").read_text(encoding="utf-8").splitlines()[:3]
    assert header[0] == "# This file was autogenerated by uv via the following command:"
    assert "uv export" in header[1]
    assert "--frozen" in header[1]
    assert "--no-dev" in header[1]
    assert "--no-hashes" not in header[1]
    assert "--hash=sha256:" in (ROOT / "requirements.txt").read_text(
        encoding="utf-8"
    )
    assert "pytest" not in _exported_packages()
    assert "pytest-asyncio" not in _exported_packages()


def test_requirements_export_has_no_lockfile_drift() -> None:
    result = subprocess.run(
        [
            str(ROOT / ".tools" / "uv"),
            "export",
            "--frozen",
            "--no-dev",
            "--format",
            "requirements-txt",
            "--no-emit-project",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    committed = (ROOT / "requirements.txt").read_text(encoding="utf-8").splitlines()
    generated = result.stdout.splitlines()
    # uv records the invocation in the first two comment lines. The committed
    # export additionally records its output filename; dependency content must
    # otherwise be byte-for-byte equivalent.
    assert committed[2:] == generated[2:]


def test_python_version_matches_bootstrap_runtime() -> None:
    assert (ROOT / ".python-version").read_text(encoding="utf-8").strip() == "3.11.15"
    bootstrap = (ROOT / "bootstrap.sh").read_text(encoding="utf-8")
    assert 'PYTHON_VERSION="3.11.15"' in bootstrap
    assert '--no-build --python "$PYTHON_VERSION"' in bootstrap
