"""Small encrypted store for registry credentials.

Registry metadata remains human-readable under ``data/`` while credential-
bearing fields are encrypted into the ignored project runtime directory.  The
stable control-plane token generated by bootstrap derives the local encryption
key; it is never written into registry files.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import tempfile
import threading
from pathlib import Path
from typing import Any, Mapping, Optional

from cryptography.fernet import Fernet, InvalidToken

from .storage_paths import (
    UnsafeStoragePathError,
    ensure_real_directory,
    validate_regular_file,
)


class SecretStoreError(RuntimeError):
    pass


class EncryptedSecretStore:
    def __init__(self, path: Path, token: Optional[str] = None):
        self.path = Path(path)
        self._token = token
        self._lock = threading.RLock()

    def _cipher(self) -> Fernet:
        token = self._token or os.environ.get("AGENT_BUILDER_API_TOKEN", "")
        if len(token.strip()) < 32:
            raise SecretStoreError("Registry credential encryption is not configured")
        key = base64.urlsafe_b64encode(hashlib.sha256(token.strip().encode("utf-8")).digest())
        return Fernet(key)

    def _load(self) -> dict[str, Any]:
        try:
            validate_regular_file(self.path, allow_missing=True)
            if not self.path.exists():
                return {}
            plaintext = self._cipher().decrypt(self.path.read_bytes())
            decoded = json.loads(plaintext.decode("utf-8"))
        except (
            InvalidToken,
            UnicodeDecodeError,
            json.JSONDecodeError,
            UnsafeStoragePathError,
        ) as exc:
            raise SecretStoreError("Unable to decrypt registry credentials") from exc
        if not isinstance(decoded, dict):
            raise SecretStoreError("Encrypted registry credential payload is invalid")
        return decoded

    def get_many(self, keys: list[str]) -> dict[str, Any]:
        with self._lock:
            if not self.path.exists():
                return {}
            values = self._load()
            return {key: values[key] for key in keys if key in values}

    def set_many(self, updates: Mapping[str, Any]) -> None:
        with self._lock:
            # Do not require a key just to persist a registry that has never
            # contained credentials.
            if not self.path.exists() and all(value is None for value in updates.values()):
                return
            values = self._load()
            for key, value in updates.items():
                if value is None:
                    values.pop(key, None)
                else:
                    values[key] = value

            if not values:
                self.path.unlink(missing_ok=True)
                return

            try:
                ensure_real_directory(self.path.parent)
                validate_regular_file(self.path, allow_missing=True)
            except UnsafeStoragePathError as exc:
                raise SecretStoreError("Registry credential path is unsafe") from exc
            payload = json.dumps(values, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
            encrypted = self._cipher().encrypt(payload)
            fd, temporary_name = tempfile.mkstemp(
                prefix=f".{self.path.name}.", suffix=".tmp", dir=self.path.parent
            )
            try:
                with os.fdopen(fd, "wb") as handle:
                    handle.write(encrypted)
                    handle.flush()
                    os.fsync(handle.fileno())
                os.chmod(temporary_name, 0o600)
                os.replace(temporary_name, self.path)
            finally:
                if os.path.exists(temporary_name):
                    os.unlink(temporary_name)


_store: Optional[EncryptedSecretStore] = None
_store_lock = threading.Lock()


def get_registry_secret_store() -> EncryptedSecretStore:
    global _store
    if _store is None:
        with _store_lock:
            if _store is None:
                project_root = Path(__file__).resolve().parent.parent
                runtime_root = Path(
                    os.environ.get("AGENT_BUILDER_RUNTIME_DIR", project_root / ".runtime")
                )
                _store = EncryptedSecretStore(
                    runtime_root / "secrets" / "registry-secrets.enc"
                )
    return _store
